### ISSUE TITLE
[one.vmpool.info] User couldn't be authenticated, aborting call.

### ISSUE THREAD

**Issue by gdakuzak** [iddqdby/phponeapi#2]
Hello,

I try call vm info like this post (https://forum.opennebula.org/t/opennebula-php-api/6729/3), but just return message: 

[one.vmpool.info] User couldn't be authenticated, aborting call.

Do you have solution ?

**Comment by mvdve** [comment]
Hi,

The error message is pretty clear: The user credentials which you use are not correct.

Make sure the user name and password are correct by checking them via the UI.
